### PR TITLE
Fix dashboard mana event feed

### LINKED ISSUE #1083: Mana Dashboard detaches on browser refresh
## Bug description

With everything working and in sync, when I refresh my browser on page http://x.x.x.x:8081/mana, I get the warning `WARNING: Node not in sync, displayed mana values might be outdated!` and the page eventually crashes.

Rectified by clicking Dashboard on menu, then reentering by clicking Mana in menu. 'Back' in browser does not work. 

## GoShimmer version

0.5.2

## Hardware specification

Hetzner CX21
2 VCPU
4 GB RAM
40 GB DISK LOCAL

Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)

## Steps To reproduce the bug

1. Refresh :8081/mana in Google Chrome
2. 
3. 

## Expected behaviour

Stats update, return to functional page

## Actual behaviour

Chart and node mana details go to zero. 

Access and Consensus Events do still update.

Page eventually crashes

## Errors
`Aw snap, something went wrong. Error code 6`

Screenshot 2021-03-17 at 12 45 09

### PR DESCRIPTION
**Pull request by lzpap**
Fixes #1083 

Refactored mana events handling in dashboards.

### CODE REVIEW

File: plugins/analysis/dashboard/frontend/src/app/stores/ManaStore.tsx [hunk 1]
```diff
@@ -189,55 +214,142 @@ export class ManaStore {
...
 
     @action
-    addNewPledge = (msg: IPledgeMessage) => {
+    addNewInitPledge = (msg: IPledgeMessage) => {
+        let store: Array<ManaEvent> = [];
         switch (msg.manaType) {
             case "Access":
-                this.handleNewPledgeEvent(this.accessEvents, msg);
+                store = this.initAccessEvents;
+                if (store.length > maxEventsStored) {
```
Comment (jkrvivian) [inline plugins/analysis/dashboard/frontend/src/app/stores/ManaStore.tsx:222]: `>=`?

**Review by capossele — APPROVED** [review]
