### PR TITLE
Fix global worker pool contention

### LINKED ISSUE #2507: Buffer/Consumer scheme for high-contention components
* Currently, event handlers are executed from the main workerpool workers: if the actions described in the event handler are not highly parallelizable (i.e. they lock on the same lock), all these workers are just stuck waiting for the lock.
* A better design would be to have a separate event consumer worker that deals with such tasks _sequentially_. The eventloop workers will then just push to a queue that the mentioned consumer consumes.
* We could pontentially change the `Attach` method to optionally pass a dedicated unbounded queue workerpool, using which, such event in consumed through.

### PR DESCRIPTION
**Pull request by jonastheis**
# Description of change

This PR solves the global worker pools contention problem, where all/many workers of the global event loop/worker pool were competing for the same lock. This is done by adding separate consumers to tasks that are prone to create contention. In code this reflects via specifying a distinct worker pool when attaching to an event.

It updates the Grafana dashboard `GoShimmer Local Metrics` to show all worker pools
image

Fixes #2507

### CODE REVIEW

File: packages/protocol/engine/clock/clock.go [hunk 1]
```diff
@@ -74,28 +70,28 @@ func (c *Clock) SetConfirmedTime(confirmedTime time.Time) (updated bool) {
...
-	return c.lastConfirmedTime.Add(time.Since(c.lastConfirmedTimeUpdated))
+	return c.lastConfirmed.Time.Add(time.Since(c.lastConfirmed.Updated))
 }
 
-// updateTime updates the given time parameter if the given time larger than the current time.
-func (c *Clock) updateTime(now, newTime time.Time, param, updatedParam *time.Time) (updated bool) {
-	c.mutex.Lock()
-	defer c.mutex.Unlock()
+// updateTime updates the given Time parameter if the given Time larger than the current Time.
+func (c *Clock) updateTime(t *timeUpdate, now, newTime time.Time) (updated bool) {
```
Comment (alexsporn) [inline packages/protocol/engine/clock/clock.go]: move this to timeUpdate struct as a func

File: plugins/prometheus/workerpool.go [hunk 2]
```diff
@@ -6,35 +6,46 @@ import (
 )
 
 var (
-	workerCount  prometheus.Gauge
-	pendingTasks prometheus.Gauge
+	// workerCount  prometheus.Gauge
```
Comment (alexsporn) [inline plugins/prometheus/workerpool.go]: remove commented out code

File: packages/protocol/congestioncontrol/congestioncontrol.go [hunk 3]
```diff
@@ -14,16 +15,22 @@ import (
...
 
 func New(opts ...options.Option[CongestionControl]) (congestionControl *CongestionControl) {
-	return options.Apply(&CongestionControl{
-		Events: NewEvents(),
+	congestionControl = options.Apply(&CongestionControl{
+		Events:     NewEvents(),
+		workerPool: workerpool.NewUnboundedWorkerPool(1),
 	}, opts)
+
+	congestionControl.workerPool.Start()
```
Comment (karimodm) [inline packages/protocol/congestioncontrol/congestioncontrol.go:31]: Only start the workerpool when you actually setup events. Like the retainer.

File: packages/protocol/engine/engine.go [hunk 4]
```diff
@@ -346,17 +355,19 @@ func (e *Engine) initBlockStorage() {
...
+	}), 1)
+	e.Tangle.Events.BlockDAG.BlockOrphaned.AttachWithWorkerPool(event.NewClosure(func(block *blockdag.Block) {
 		if err := e.NotarizationManager.NotarizeOrphanedBlock(block.ModelsBlock); err != nil {
 			e.Events.Error.Trigger(errors.Errorf("failed to remove orphaned block %s from epoch: %w", block.ID(), err))
 		}
-	}))
+	}), wp)
+	e.workerPools["NotarizationManager.Blocks"] = wp
 
+	// TODO: Why is it hooked?
```
Comment (karimodm) [inline packages/protocol/engine/engine.go:370]: If I recall correctly, it was initially to prevent the ledger from persisting Transactions in the statediffs out of order whenever the processed transaction spend from each other. This could be problematic in the case a transaction needs to be moved to another epoch, or deleted altogether. You have to be able to make sense of the outputs you are spending and creating in each epoch, and if such accepted transaction are not dealt with in order some inconsistencies might arise in the statediffs for each epoch: although unlikely, we wanted to play it safe!

**Review by karimodm — APPROVED** [review]
