### PR TITLE
Fix graceful shutdown

### LINKED ISSUE #504: FPC voter server doesn't shuttdown cleanly sometimes
The FPC voter server sometimes is unable to shutdown cleanly within a one minute time period.

### PR DESCRIPTION
**Pull request by capossele**
This PR fixes #504 .
It was actually the client-analysis not shutting-down if it was not able to connect to the server-analysis.

### CODE REVIEW

File: packages/vote/net/server.go [hunk 1]
```diff
@@ -71,12 +73,16 @@ func (vs *VoterServer) Run() error {
 		return err
 	}
 
+	vs.grpcServerMutex.Lock()
 	vs.grpcServer = grpc.NewServer()
+	vs.grpcServerMutex.Unlock()
```
Comment (Wollac) [inline packages/vote/net/server.go:78]: i am not 100% sure how grpc works, but I guess the `GracefulStop` only makes sense after a `Serve`. Thus, I would just defer the `Unlock` to also protect the register and serve.

File: packages/vote/net/server.go [hunk 2]
```diff
@@ -71,12 +73,16 @@ func (vs *VoterServer) Run() error {
...
 	RegisterVoterQueryServer(vs.grpcServer, vs)
 
 	return vs.grpcServer.Serve(listener)
 }
 
 func (vs *VoterServer) Shutdown() {
+	vs.grpcServerMutex.RLock()
+	defer vs.grpcServerMutex.RUnlock()
 	vs.grpcServer.GracefulStop()
```
Comment (Wollac) [inline packages/vote/net/server.go:87]:
```suggestion
	if vs.grpcServer != nil {
		vs.grpcServer.GracefulStop()
	}
```

File: packages/vote/net/server.go (hunk 1 above)
Comment (capossele) [reply packages/vote/net/server.go:78]: Actually what needs to be protected here is only the assignment, because it might happen that the Shutdown() is getting called by a different goroutine, while we are assigning the pointer.

Comment (Wollac) [reply packages/vote/net/server.go:78]: But what would happen now when both are called at the same time? `GracefulStop` could be completely executed and then we reach the `vs.grpcServer.Serve()` in `Run()`. Is then the server running although we called `Shutdown` at the same time?

Comment (capossele) [reply packages/vote/net/server.go]: Ok, I've removed the initial goroutine, so that the shutdown gets called only after the assignment.
